apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: week1-app
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: week1
  git:
    checkout:
      ref:
        branch: main
    commit:
      author: fluxbot
      message: "ci: update image {{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: main
  update:
    path: ./k3s
    strategy: Setters
